export default {
  files: [
    "packages/server/src/**/*.ts",
    "packages/server/test/coverage.test.ts",
    "packages/server/test/globs.test.ts",
    "packages/server/test/properties.test.ts",
    "vitest.mutation.config.ts",
    "tsconfig.base.json",
    "package.json",
    "pnpm-lock.yaml",
  ],
  testRunner: "vitest",
  plugins: ["@stryker-mutator/vitest-runner"],
  vitest: { configFile: "vitest.mutation.config.ts" },
  mutate: ["packages/server/src/coverage.ts", "packages/server/src/globs.ts"],
  reporters: ["clear-text", "json", "html"],
  jsonReporter: { fileName: "reports/mutation/mutation.json" },
  htmlReporter: { fileName: "reports/mutation/index.html" },
  thresholds: { high: 90, low: 80, break: 80 },
  concurrency: 2,
  timeoutMS: 10000,
  timeoutFactor: 2,
  tempDirName: ".stryker-tmp",
  cleanTempDir: true,
};
