// Build the committed Claude Code plugin bundle under plugin/.
// Bundles the server and crw CLI to single ESM files (node:sqlite is a
// builtin, so no native deps), copies scip.proto next to the server bundle,
// and copies the built web UI. The scip indexer packages are NOT bundled —
// the plugin's SessionStart hook npm-installs them into ${CLAUDE_PLUGIN_DATA}
// (see plugin/package.json + plugin/hooks/hooks.json).
//
// Run after `pnpm build`:  node scripts/build-plugin.mjs
import { build } from "esbuild";
import { cpSync, copyFileSync, mkdirSync, rmSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "plugin");

const webDist = join(root, "packages/web/dist");
if (!existsSync(join(webDist, "index.html"))) {
  console.error("web UI not built — run `pnpm build` first");
  process.exit(1);
}

const common = {
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  // createRequire-based resolution (indexer bins) must stay dynamic.
  logOverride: { "require-resolve-not-external": "silent" },
  // CJS deps (cross-spawn etc.) dynamically require node builtins; esbuild's
  // ESM shim throws on those unless a real `require` exists at top level.
  banner: {
    js: [
      "// Generated by scripts/build-plugin.mjs — do not edit.",
      "import { createRequire as __createRequire } from 'node:module';",
      "const require = __createRequire(import.meta.url);",
    ].join("\n"),
  },
};

rmSync(join(out, "dist"), { recursive: true, force: true });
rmSync(join(out, "web"), { recursive: true, force: true });
mkdirSync(join(out, "dist"), { recursive: true });

await build({ ...common, entryPoints: [join(root, "packages/server/src/index.ts")], outfile: join(out, "dist/server.js") });
await build({ ...common, entryPoints: [join(root, "packages/skill/src/cli.ts")], outfile: join(out, "dist/crw.js") });
copyFileSync(join(root, "packages/server/src/graph/scip.proto"), join(out, "dist/scip.proto"));
cpSync(webDist, join(out, "web"), { recursive: true });

// The plugin SKILL.md is packages/skill/skill.md with two plugin-mode swaps:
// the crw invocation (env-prefixed bundle call instead of the repo binary)
// and the indexer-install note (repo devs get indexers via pnpm). Generated
// here so the two files can never drift; the CI freshness guard covers it.
const PLUGIN_INVOCATION = `Every \`crw\` command below is run as:

\`\`\`bash
CRW_DATA_DIR="\${CLAUDE_PLUGIN_DATA}" CRW_INDEXER_HOME="\${CLAUDE_PLUGIN_DATA}" node "\${CLAUDE_PLUGIN_ROOT}/dist/crw.js" <command>
\`\`\`

The env prefix is required on every invocation (state and indexers live in the
plugin data dir, never in the reviewed repo). Requires Node >= 22.13. Every
command prints JSON on stdout; add \`--pretty\` for human-readable output. Never
touch the SQLite file or hand-roll \`curl\` — the CLI is the stable surface.`;

const LANGUAGE_SUPPORT = `Language support: TypeScript and Python indexers are installed automatically
(first session start runs \`npm install\` in the plugin data dir — allow a
minute once). Java additionally needs the scip-java toolchain on PATH
(coursier \`cs\` + JDK + Maven); without it Java changes appear as residual-only
with a visible warning — relay that warning, it is expected degradation, not
an error.
`;

const skillSrc = readFileSync(join(root, "packages/skill/skill.md"), "utf8");
const generated = skillSrc
  .replace(/^<!--[\s\S]*?-->\n/, "") // source-of-truth header comment
  .replace(
    /<!-- crw-invocation:start[\s\S]*?crw-invocation:end -->/,
    PLUGIN_INVOCATION
  )
  .replace(/<!-- plugin:language-support[^>]*-->\n/, `${LANGUAGE_SUPPORT}\n`);
for (const marker of ["crw-invocation", "plugin:language-support"]) {
  if (!generated.includes("CLAUDE_PLUGIN_ROOT") || generated.includes(marker)) {
    console.error(`SKILL.md generation failed: marker '${marker}' did not resolve — check packages/skill/skill.md`);
    process.exit(1);
  }
}
writeFileSync(join(out, "skills/code-review-walkthrough/SKILL.md"), generated);

console.log("plugin bundle written to plugin/dist + plugin/web (+ generated SKILL.md)");
