// Build the committed Claude Code plugin bundle under plugin/.
// Bundles the server and crw CLI to single ESM files (node:sqlite is a
// builtin, so no native deps), copies scip.proto next to the server bundle,
// and copies the built web UI. The scip indexer packages are NOT bundled —
// the plugin's SessionStart hook npm-installs them into ${CLAUDE_PLUGIN_DATA}
// (see plugin/package.json + plugin/hooks/hooks.json).
//
// Run after `pnpm build`:  node scripts/build-plugin.mjs
import { build } from "esbuild";
import { cpSync, copyFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "plugin");

const webDist = join(root, "packages/web/dist");
if (!existsSync(join(webDist, "index.html"))) {
  console.error("web UI not built — run `pnpm build` first");
  process.exit(1);
}

const common = {
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  // createRequire-based resolution (indexer bins) must stay dynamic.
  logOverride: { "require-resolve-not-external": "silent" },
  // CJS deps (cross-spawn etc.) dynamically require node builtins; esbuild's
  // ESM shim throws on those unless a real `require` exists at top level.
  banner: {
    js: [
      "// Generated by scripts/build-plugin.mjs — do not edit.",
      "import { createRequire as __createRequire } from 'node:module';",
      "const require = __createRequire(import.meta.url);",
    ].join("\n"),
  },
};

rmSync(join(out, "dist"), { recursive: true, force: true });
rmSync(join(out, "web"), { recursive: true, force: true });
mkdirSync(join(out, "dist"), { recursive: true });

await build({ ...common, entryPoints: [join(root, "packages/server/src/index.ts")], outfile: join(out, "dist/server.js") });
await build({ ...common, entryPoints: [join(root, "packages/skill/src/cli.ts")], outfile: join(out, "dist/crw.js") });
copyFileSync(join(root, "packages/server/src/graph/scip.proto"), join(out, "dist/scip.proto"));
cpSync(webDist, join(out, "web"), { recursive: true });

console.log("plugin bundle written to plugin/dist + plugin/web");
